fix: add missing Properties
CycloneDX/cyclonedx-go pull request #39
Opened 2022-05-19 13:31 UTC by desenna

Closes https://github.com/CycloneDX/cyclonedx-go/issues/38

2022-05-19 18:20 UTC, nscuro requested changes
Thanks for the PR @desenna! 

Besides `TestVulnerability_Properties` currently panicking, the snapshot files for `valid-vulnerability.json` and `valid-vulnerability.xml` have to be updated.

You can do that by running

```shell
UPDATE_SNAPSHOTS=true make test
```

2022-05-19 18:20 UTC, nscuro commented on cyclonedx_test.go
> +	assert.Equal(t, 0, len(*vuln.Properties))
This will always panic, because `vuln.Properties` is `nil`.

2022-05-19 19:59 UTC, nscuro commented
Welp, looks like you discovered a bug in the XML schema! 🚀

I filed a bug for this in the specification repo: https://github.com/CycloneDX/specification/issues/147

Unfortunate, but it may take some time for the schema to be updated. For now you could comment out the properties in `valid-vulnerability.xml` (but not the JSON file) and regenerate the snapshots. That should make the test pass.

2022-05-19 20:33 UTC, desenna commented
Yep, discovered a bug. Just wanted to check with my teammate that I wasn't crazy. Ok, going to add new commit now.

2022-05-19 20:33 UTC, desenna commented
It points to lack of tests.

2022-05-19 20:53 UTC, desenna commented on testdata/valid-vulnerability.xml
> +            <!-- <properties>
TODO: https://github.com/CycloneDX/cyclonedx-go/issues/40

2022-05-20 12:36 UTC, nscuro approved these changes

2022-05-20 12:39 UTC, merged

2022-05-20 13:41 UTC, desenna commented
Thanks for merging @nscuro . Any idea when this can be released as a v0.5.3 so we can use it? If easy to do, would it be possible to release today so I don't have to code a workaround on my side and then undo it? 😉

2022-05-20 13:48 UTC, nscuro commented
I'm on the go currently but I'll most likely release v0.6.0 later today. Give me 1-2 hours.

2022-05-20 15:14 UTC, nscuro commented
@desenna Just pushed v0.6.0. Thanks again for your PR!

2022-05-20 15:49 UTC, desenna commented
> @desenna Just pushed v0.6.0. Thanks again for your PR!

Thanks @nscuro !!